version: '3'

networks:
  default:
    driver: bridge

services:
  proxy:
    image: traefik
    command: --api --docker
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./conf:/etc/traefik/conf
